poetry:
  path: xxx
server:
    port: 9991
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/poetry?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&rewriteBatchedStatements=true
    username: root
    password: xxx
    hikari:
      keepalive-time: 120000
      max-lifetime: 300000
  jackson:
    default-property-inclusion: non_null
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
meilisearch:
  host-url: xxx
  api-key: xxx
  index-name: xxx